### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jasonkuhrt**
Tidy example

### CODE REVIEW

**Comment by sokra** [comment]
@DanielApt

**Comment by DanielApt** [comment]
I prefer your code example, but would still like to keep
> When using `webpack.config.js`, simply prepend `mocha!` in front of the entry:

in the example.

**Comment by jasonkuhrt** [comment]
@DanielApt I thought about that but felt the title followed by the example made the point better. The sentence is only repeating what is otherwise easier to parse without it. Just my 0.02.

**Comment by jasonkuhrt** [comment]
If we want to move forward just accept the PR and @DanielApt et al can re-tweak it. I am not going to start a PR war or something. But this PR is how I think it reads best. Just change it again if you disagree?

**Comment by DanielApt** [comment]
@jasonkuhrt Whoops, sorry, I meant to respond to your recent comment, but it somehow slipped my mind!

No need for a PR war whatsoever, you've evidently considered all options, and I trust your judgement. I'm happy that it got merged.

**Comment by jasonkuhrt** [comment]
@DanielApt Cheers! Thanks.

**Pull request merged**
