### PR TITLE
Upgrade all deps and allow mocha-3.0.0

### PR DESCRIPTION
**Pull request by AviVahl**
mocha 3.0.0 was finally released yesterday.
I used this opportunity to upgrade deps as well.
Please consider merging and releasing a new official version of mocha-loader.

Thank you in advance.

Btw, I've tested it locally (in webpack-dev-server) and works as expected.

### CODE REVIEW

**Comment by AviVahl** [comment]
Also, another approach can be to use:
`"mocha": "*"`
This will allow any version of mocha to be used in conjunction with mocha-loader.
That's how karma-mocha does it.

Please let me know which way you prefer, and I can quickly adjust the pull request.

**Comment by AviVahl** [comment]
Hi Webpack team, can this please be reviewed?
Small change that stops us from upgrading to mocha-3.0.0 (and its important bug fixes).

**Comment by AviVahl** [comment]
Hi @sokra 
I was wondering if this pull request can be reviewed, merged, and even trigger a release. It is a small change, and would allow us to finally use mocha 3.x.

Thanks in advance.

**Comment by tricoder42** [comment]
Hey @AviVahl,
thank you for this PR! 👍  I'll sync with the rest of the team and we'll merged it soon ⚡  (hopefully tomorrow).

Sorry for the delay!

**Comment by AviVahl** [comment]
Much appreciated!

**Comment by AviVahl** [comment]
@tricoder42 thank you (!!) for merging.
Is the mocha-loader team planning a release (containing this fix) any time soon?

P.S. sorry for bugging you guys about this, it just such a small change that could potentially make our team's TDD lives much easier. :o

**Pull request merged**
