### PR TITLE
Permits all mocha setup options

### PR DESCRIPTION
**Pull request by akofman**
It's not possible to configure all setup options with the actual version.
I just gave all the query to the mocha setup in order to have access to the following options :

```
- `ui` name "bdd", "tdd", "exports" etc
- `reporter` reporter instance, defaults to `mocha.reporters.spec`
- `globals` array of accepted globals
- `timeout` timeout in milliseconds
- `retries` number of times to retry failed tests
- `bail` bail on the first test failure
- `slow` milliseconds to wait before considering a test slow
- `ignoreLeaks` ignore global leaks
- `fullTrace` display the full stack-trace on failing
- `grep` string or regexp to filter tests with
```

Also I updated some dependencies versions.

Thanks for the reviews !

### CODE REVIEW

**Comment by akofman** [comment]
Any feedback ?

**Comment by JanKanty** [comment]
Feedback will be soon ;) Pls fix conflicts in the meantime

**Comment by akofman** [comment]
Hello @JanKanty , 

It is rebased ! There is some Travis errors but not related to this PR ... maybe because the .travis.yml file is missing ?

**Comment by JanKanty** [comment]
Don't look at travis status. It's not working properly yet. But you have some merge conflicts. So fix them pls.

**Comment by akofman** [comment]
Rebased !

**Pull request merged**
